apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: istio-system
spec:
  addresses:
    - 1.1.1.1/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: istio-system
spec:
  ipAddressPools:
    - first-pool
